[package]
name = "imgedit"
version = "0.1.0"
authors = ["Jaakko Lipsanen <jaakko.lipsanen@outlook.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
simple-error = "0.1.13"
lodepng = "2.0.0"
num = "0.2.0"
rand = "0.6.5"